name: Build

on:
  push:
    branches: [ master, dev ]
    paths-ignore:
      - "**/README.md"
      - lib/simple_active_link_to/version.rb
  pull_request:
    branches: [ master, dev ]
    paths-ignore:
      - "**/README.md"
      - lib/simple_active_link_to/version.rb

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0]
        rails: ['5.0', '5.1', '5.2', '6.0', '6.1']
    env:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_GEMFILE: test/gemfiles/${{ matrix.rails }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
